application: cometiphrd
version: 18
runtime: python27
api_version: 1
threadsafe: false
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (README)|
 (CHANGELOG)|
 (Makefile)|
 (doc/.*)|
 (manage.py)|
 (appengine_django/management/commands/.*)|
 (.bak)| 
 (.sass-cache/.*)|
 (.git/.*)|
 (.swp)|
 (old/.*)| 
 (.dart)|
 (.tmpl)|
 )$

builtins:
- remote_api: off
- appstats: off
- deferred: off
- django_wsgi: on


inbound_services:
- warmup


libraries:
- name: django
  version: latest  
  

handlers:

- url: /css
  static_dir: css
  secure: optional
  expiration: "1m"
  
#- url: /js
#  static_dir: js
#  secure: optional
#  expiration: "1m"

- url: /static
  static_dir: static
  secure: optional
  
- url: /templates
  static_dir: templates
  secure: optional  

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
