application: cometiphrd
version: 17
runtime: python27
api_version: 1
threadsafe: false
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (README)|
 (CHANGELOG)|
 (Makefile)|
 (doc/.*)|
 (manage.py)|
 (appengine_django/management/commands/.*)|
 (.bak)| 
 (.sass-cache/.*)|
 )$

builtins:
- remote_api: off
- appstats: off
- django_wsgi: off
- deferred: on


#inbound_services:
#- mail
#- warmup


libraries:
- name: django
  version: latest  
#  version: "1.2"  
- name: webapp2
  version: latest  
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
- name: PIL
  version: latest

  
handlers:

- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /css
  static_dir: css
  secure: optional

- url: /js
  static_dir: js
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
   

- url: /api/.*
  script: static.app

- url: /error/.*
  script: static.app
  
- url: /.*
  script: main.app 
