application: cometiphrd
version: disabled_registration
#version: test

runtime: python27
api_version: 1
threadsafe: false


#instance_class: F1
#automatic_scaling:
#  min_idle_instances: 1
#  max_pending_latency: 1s


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/sass-cache/.*



inbound_services:
#- warmup
#- mail


libraries:
- name: django
#  version: latest  
  version: "1.4"  
- name: webapp2
  version: latest  
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
- name: PIL
  version: latest
  
builtins:
- appstats: off  
- remote_api: on
  
#dispatch:  
# Send any domain/sub-domain with a path that starts with “work” to the static backend module. 
#- url: "*/api*"
#  module: goapi
      
handlers:

- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /css
  static_dir: css
  secure: optional

- url: /js
  static_dir: js
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
   

- url: /api/.*
  script: static.app

- url: /error/.*
  script: static.app
  
- url: /.*
  script: main.app 
